#ifndef _DEPENDS_H
#define _DEPENDS_H
#include <bitset>
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <regex>
#include <iomanip>
#include <cstdlib>
#include <cstring>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/tcp.h>   
#include <netinet/ip.h>
#include <arpa/inet.h>
#include <errno.h>
#include <vector>
#include <iterator>
#include <curl/curl.h>
#include <time.h>
#include <netdb.h>
#include <assert.h>
#endif
